/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: packet.proto */

#ifndef PROTOBUF_C_packet_2eproto__INCLUDED
#define PROTOBUF_C_packet_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Packet Packet;


/* --- enums --- */


/* --- messages --- */

struct  _Packet
{
  ProtobufCMessage base;
  ProtobufCBinaryData payload;
  int32_t len;
  int64_t uuid;
  int32_t seq;
  int32_t crc;
};
#define PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&packet__descriptor) \
    , {0,NULL}, 0, 0, 0, 0 }


/* Packet methods */
void   packet__init
                     (Packet         *message);
size_t packet__get_packed_size
                     (const Packet   *message);
size_t packet__pack
                     (const Packet   *message,
                      uint8_t             *out);
size_t packet__pack_to_buffer
                     (const Packet   *message,
                      ProtobufCBuffer     *buffer);
Packet *
       packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   packet__free_unpacked
                     (Packet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Packet_Closure)
                 (const Packet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor packet__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_packet_2eproto__INCLUDED */
